spring.profiles.active=dev

spring.application.name=food-mood-journal-app

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
logging.level.org.hibernate.persister.entity=ERROR