spring.application.name=food-mood-journal-app

spring.profiles.active=dev

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
logging.level.org.hibernate.persister.entity=ERROR

insights.service.url=${INSIGHTS_SERVICE_URL:http://localhost:8081}

server.error.whitelabel.enabled=false
server.error.include-message=always
